worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include mime.types;

    upstream backend_servers {
        # Round-robin Load balancing across multiple backend instances
        server host.docker.internal:8081; # Backend Instance 1
        server host.docker.internal:8082; # Backend Instance 2
    }

    server {
        listen 80;
        server_name localhost;

        location /api/ {
            proxy_pass http://backend_servers/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # Setup for frontend static files
        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }
    }
}
