spring:
  application:
    name: payment-system
  data:
    mongodb:
      uri: mongodb+srv://reksitrajan01:8n4SHiaJfCZRrimg@cluster0.mperr.mongodb.net/test?retryWrites=true&w=majority
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  mail:
    host: smtp.gmail.com
    port: 587
    username: saiarun0109@gmail.com
    password: dvjd kstx farq jjnl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 4261656C64756E6720536563726574204B657920466F72204A575420546F6B656E2047656E65726174696F6E
  expiration: 86400000
