spring:
  application:
    name: payment-system
  data:
    mongodb:
      uri: mongodb://localhost:27017/juspay
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max.block.ms: 2000
        request.timeout.ms: 2000
        delivery.timeout.ms: 5000
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        session.timeout.ms: 10000
        request.timeout.ms: 5000
    listener:
      auto-startup: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: saiarun0109@gmail.com
    password: dvjd kstx farq jjnl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

jwt:
  secret: 4261656C64756E6720536563726574204B657920466F72204A575420546F6B656E2047656E65726174696F6E
  expiration: 86400000
